In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df = pd.read_csv('/content/drive/My Drive/Dataset/house-prices.csv')

In [4]:
df

Home     Price    SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0       1  114300.0  1790.0         2          2       2    No         East
1       2  114200.0  2030.0         4          2       3    No         East
2       3  114800.0  1740.0         3          2       1    No         East
3       4   94700.0  1980.0         3          2       3    No         East
4       5  119800.0  2130.0         3          3       3    No         East
..    ...       ...     ...       ...        ...     ...   ...          ...
123   124       NaN  1900.0         3          3       3   Yes         East
124   125  147900.0  2160.0         4          3       3   Yes         East
125   126  113500.0  2070.0         2          2       2    No        North
126   127  149900.0  2020.0         3          3       1    No         West
127   128  124600.0  2250.0         3          3       4    No        North

[128 rows x 8 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Home          128 non-null    int64  
 1   Price         118 non-null    float64
 2   SqFt          117 non-null    float64
 3   Bedrooms      128 non-null    int64  
 4   Bathrooms     128 non-null    int64  
 5   Offers        128 non-null    int64  
 6   Brick         128 non-null    object 
 7   Neighborhood  128 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 8.1+ KB


In [6]:
df.describe()

Home          Price         SqFt    Bedrooms   Bathrooms  \
count  128.000000     118.000000   117.000000  128.000000  128.000000   
mean    64.500000  130599.152542  2002.905983    3.023438    2.445312   
std     37.094474   27631.712537   215.046346    0.725951    0.514492   
min      1.000000   69100.000000  1450.000000    2.000000    2.000000   
25%     32.750000  111175.000000  1880.000000    3.000000    2.000000   
50%     64.500000  125700.000000  2000.000000    3.000000    2.000000   
75%     96.250000  150125.000000  2150.000000    3.000000    3.000000   
max    128.000000  211200.000000  2590.000000    5.000000    4.000000   

           Offers  
count  128.000000  
mean     2.578125  
std      1.069324  
min      1.000000  
25%      2.000000  
50%      3.000000  
75%      3.000000  
max      6.000000

In [7]:
df.groupby('Brick').size()

Brick
No     86
Yes    42
dtype: int64

In [8]:
df.groupby('Neighborhood').size()

Neighborhood
East     45
North    44
West     39
dtype: int64

In [9]:
df.isnull().sum()

Home             0
Price           10
SqFt            11
Bedrooms         0
Bathrooms        0
Offers           0
Brick            0
Neighborhood     0
dtype: int64

In [10]:
df['Price'] = df['Price'].fillna(df['Price'].median())
df['SqFt'] = df['SqFt'].fillna(df['Price'].median())

In [11]:
X = df.iloc[:, 2:8].values
y = df.iloc[:, 1].values

In [12]:
X

array([[1790.0, 2, 2, 2, 'No', 'East'],
       [2030.0, 4, 2, 3, 'No', 'East'],
       [1740.0, 3, 2, 1, 'No', 'East'],
       [1980.0, 3, 2, 3, 'No', 'East'],
       [2130.0, 3, 3, 3, 'No', 'East'],
       [1780.0, 3, 2, 2, 'No', 'North'],
       [1830.0, 3, 3, 3, 'Yes', 'West'],
       [2160.0, 4, 2, 2, 'No', 'West'],
       [2110.0, 4, 2, 3, 'No', 'East'],
       [1730.0, 3, 3, 3, 'No', 'East'],
       [2030.0, 3, 2, 3, 'Yes', 'East'],
       [1870.0, 2, 2, 2, 'Yes', 'East'],
       [1910.0, 3, 2, 4, 'No', 'North'],
       [2150.0, 3, 3, 5, 'Yes', 'North'],
       [2590.0, 4, 3, 4, 'No', 'West'],
       [1780.0, 4, 2, 1, 'No', 'West'],
       [2190.0, 3, 3, 4, 'Yes', 'East'],
       [125700.0, 3, 3, 4, 'No', 'North'],
       [1700.0, 2, 2, 1, 'Yes', 'East'],
       [1920.0, 3, 3, 2, 'Yes', 'West'],
       [1790.0, 3, 2, 3, 'No', 'East'],
       [2000.0, 3, 2, 4, 'No', 'North'],
       [1690.0, 3, 2, 3, 'No', 'North'],
       [1820.0, 3, 2, 3, 'Yes', 'North'],
       [2210.0, 4, 3, 2

In [13]:
y

array([114300., 114200., 114800.,  94700., 119800., 114600., 151600.,
       150700., 119200., 104000., 132500., 123000., 125700., 126300.,
       176800., 145800., 125700.,  83600., 111400., 167200., 116200.,
       113800.,  91700., 106100., 156400., 149300., 137000.,  99300.,
        69100., 188000., 182000., 112300., 135000., 139600., 117800.,
       117100., 117500., 147000., 125700., 108200., 106600., 133600.,
       105600., 154000., 166500., 103200., 129800.,  90300., 115900.,
       125700., 151100.,  91100., 117400., 130800.,  81300., 125700.,
       140900., 152300., 125700., 155400., 180900., 100900., 161300.,
       120500., 130300., 111100., 126200., 151900.,  93600., 165600.,
       166700., 157600., 107300., 125700., 144200., 106900., 129800.,
       176500., 121300., 143600., 125700., 184300., 164800., 147700.,
        90500., 188300., 102700., 172500., 127700.,  97800., 143100.,
       116500., 125700., 157100., 160600., 152500., 133300., 126800.,
       145500., 1710

In [14]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 4] = labelencoder_X.fit_transform(X[:, 4])
X

array([[1790.0, 2, 2, 2, 0, 'East'],
       [2030.0, 4, 2, 3, 0, 'East'],
       [1740.0, 3, 2, 1, 0, 'East'],
       [1980.0, 3, 2, 3, 0, 'East'],
       [2130.0, 3, 3, 3, 0, 'East'],
       [1780.0, 3, 2, 2, 0, 'North'],
       [1830.0, 3, 3, 3, 1, 'West'],
       [2160.0, 4, 2, 2, 0, 'West'],
       [2110.0, 4, 2, 3, 0, 'East'],
       [1730.0, 3, 3, 3, 0, 'East'],
       [2030.0, 3, 2, 3, 1, 'East'],
       [1870.0, 2, 2, 2, 1, 'East'],
       [1910.0, 3, 2, 4, 0, 'North'],
       [2150.0, 3, 3, 5, 1, 'North'],
       [2590.0, 4, 3, 4, 0, 'West'],
       [1780.0, 4, 2, 1, 0, 'West'],
       [2190.0, 3, 3, 4, 1, 'East'],
       [125700.0, 3, 3, 4, 0, 'North'],
       [1700.0, 2, 2, 1, 1, 'East'],
       [1920.0, 3, 3, 2, 1, 'West'],
       [1790.0, 3, 2, 3, 0, 'East'],
       [2000.0, 3, 2, 4, 0, 'North'],
       [1690.0, 3, 2, 3, 0, 'North'],
       [1820.0, 3, 2, 3, 1, 'North'],
       [2210.0, 4, 3, 2, 1, 'East'],
       [2290.0, 4, 3, 3, 0, 'North'],
       [2000.0, 4, 2, 3, 0, 

In [15]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 5] = labelencoder_X.fit_transform(X[:, 5])
X

array([[1790.0, 2, 2, 2, 0, 0],
       [2030.0, 4, 2, 3, 0, 0],
       [1740.0, 3, 2, 1, 0, 0],
       [1980.0, 3, 2, 3, 0, 0],
       [2130.0, 3, 3, 3, 0, 0],
       [1780.0, 3, 2, 2, 0, 1],
       [1830.0, 3, 3, 3, 1, 2],
       [2160.0, 4, 2, 2, 0, 2],
       [2110.0, 4, 2, 3, 0, 0],
       [1730.0, 3, 3, 3, 0, 0],
       [2030.0, 3, 2, 3, 1, 0],
       [1870.0, 2, 2, 2, 1, 0],
       [1910.0, 3, 2, 4, 0, 1],
       [2150.0, 3, 3, 5, 1, 1],
       [2590.0, 4, 3, 4, 0, 2],
       [1780.0, 4, 2, 1, 0, 2],
       [2190.0, 3, 3, 4, 1, 0],
       [125700.0, 3, 3, 4, 0, 1],
       [1700.0, 2, 2, 1, 1, 0],
       [1920.0, 3, 3, 2, 1, 2],
       [1790.0, 3, 2, 3, 0, 0],
       [2000.0, 3, 2, 4, 0, 1],
       [1690.0, 3, 2, 3, 0, 1],
       [1820.0, 3, 2, 3, 1, 1],
       [2210.0, 4, 3, 2, 1, 0],
       [2290.0, 4, 3, 3, 0, 1],
       [2000.0, 4, 2, 3, 0, 2],
       [1700.0, 3, 2, 2, 0, 0],
       [1600.0, 2, 2, 3, 0, 1],
       [125700.0, 4, 3, 1, 1, 2],
       [2250.0, 4, 3, 3, 1, 2],
    

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state = 7)

In [17]:
X_train

array([[1780.0, 4, 2, 1, 0, 2],
       [1690.0, 3, 2, 3, 0, 1],
       [2110.0, 3, 2, 3, 0, 0],
       [2000.0, 4, 2, 3, 0, 2],
       [2000.0, 3, 2, 3, 1, 1],
       [1940.0, 2, 2, 2, 1, 0],
       [1880.0, 3, 3, 1, 1, 2],
       [1780.0, 4, 2, 1, 0, 2],
       [1790.0, 3, 2, 3, 0, 0],
       [1920.0, 3, 2, 2, 0, 1],
       [1920.0, 3, 2, 1, 1, 0],
       [125700.0, 2, 2, 1, 0, 0],
       [1860.0, 2, 2, 3, 0, 1],
       [2100.0, 3, 2, 3, 1, 0],
       [1910.0, 3, 2, 4, 0, 1],
       [1930.0, 3, 2, 2, 0, 2],
       [1870.0, 2, 2, 2, 1, 0],
       [2220.0, 4, 3, 2, 0, 2],
       [1450.0, 2, 2, 1, 1, 1],
       [1700.0, 2, 2, 1, 1, 0],
       [125700.0, 2, 2, 4, 0, 1],
       [1740.0, 3, 2, 1, 0, 0],
       [125700.0, 3, 3, 3, 1, 0],
       [125700.0, 3, 3, 4, 0, 1],
       [125700.0, 4, 3, 1, 1, 2],
       [2050.0, 2, 2, 1, 1, 2],
       [2420.0, 4, 3, 4, 0, 2],
       [2250.0, 4, 3, 3, 1, 2],
       [1890.0, 3, 2, 1, 1, 0],
       [125700.0, 3, 3, 1, 0, 2],
       [2060.0, 2, 2, 1, 1, 

In [18]:
X_test

array([[1930.0, 3, 3, 2, 0, 1],
       [1930.0, 2, 3, 3, 0, 1],
       [2250.0, 3, 3, 4, 0, 1],
       [2160.0, 4, 3, 3, 1, 0],
       [1840.0, 4, 3, 2, 0, 2],
       [1520.0, 2, 2, 3, 0, 1],
       [1900.0, 4, 2, 4, 0, 1],
       [2250.0, 3, 3, 3, 1, 0],
       [1600.0, 2, 2, 3, 0, 1],
       [2250.0, 4, 3, 2, 1, 2],
       [2140.0, 3, 3, 3, 0, 2],
       [2080.0, 3, 3, 2, 0, 0],
       [1970.0, 2, 2, 1, 1, 2],
       [1780.0, 3, 2, 2, 0, 1],
       [1700.0, 3, 2, 3, 1, 1],
       [2010.0, 3, 2, 5, 0, 1],
       [2150.0, 3, 2, 2, 0, 0],
       [2070.0, 2, 2, 2, 0, 1],
       [125700.0, 2, 3, 2, 0, 1],
       [2150.0, 2, 3, 4, 0, 1],
       [1880.0, 2, 2, 2, 0, 1],
       [2140.0, 4, 3, 2, 1, 2],
       [1810.0, 3, 2, 3, 0, 0],
       [2150.0, 3, 3, 5, 1, 1],
       [2210.0, 3, 3, 4, 0, 1],
       [1650.0, 3, 2, 3, 0, 1]], dtype=object)

In [19]:
y_train

array([143600.,  91700., 108700., 137000., 115700., 123600., 172500.,
       145800., 116200., 117800., 154000., 106600.,  91100., 151100.,
       125700., 129800., 123000., 161300., 111100., 111400., 109700.,
       114800., 117000.,  83600., 188000., 164800., 147000., 182000.,
       134000., 125700., 144800., 145500., 171000., 133300.,  99300.,
       155400.,  94700., 139600., 166700., 113800., 125700., 146900.,
       125700., 176500., 117100., 132500., 199500., 157600., 126800.,
       112300., 125700., 124500., 114200., 108500., 102500., 125700.,
       104000., 119800., 125700., 121300., 125700., 160600., 117800.,
       130300., 100900., 130800., 123100., 156400., 140900., 165600.,
       120500.,  82300., 180900., 167200., 151600., 125700., 106900.,
       114300., 166500., 150700., 115900., 149900., 125700., 108200.,
       119200., 143100., 105600., 111600.,  97800., 107300., 105600.,
       176800., 152300., 125700., 211200., 106100., 147700., 151900.,
       150200., 1493

In [20]:
y_test

array([127700., 110400., 124600., 147900., 133600.,  90500., 102700.,
       135000.,  69100., 188300., 144200., 157100., 152500., 114600.,
       125700., 103200., 116500., 113500., 129800., 117400., 117500.,
       184300., 103200., 126300., 126200.,  81300.])

In [21]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [22]:
print("Regressor slope:  %2.f  "%( regressor.coef_[0]))
print("Regressor intercept:%2.f  "% regressor.intercept_)

Regressor slope:  -0  
Regressor intercept:61985  


In [23]:
y_pred = regressor.predict(X_test)
y_pred

array([136573.97892264, 118715.44349403, 124051.79103562, 150511.95533736,
       159088.61203976, 104912.77946275, 121850.76066938, 138904.03340243,
       104909.4257188 , 178575.99119541, 141217.50007135, 125660.97947056,
       147813.96583986, 122760.41522355, 136013.94960524, 103987.61384284,
       111838.19297562, 111144.10892875, 119781.16885   , 112451.83424256,
       111152.07407062, 178580.60259334, 105598.05993176, 137306.1638533 ,
       124053.46790759, 116511.47860183])

In [24]:
regressor.predict([[100, 2, 3, 4, 0, 2]])

array([123444.48511331])

In [25]:
from sklearn import metrics
print("MAE %2.f" %(metrics.mean_absolute_error(y_test,y_pred)))

MAE 10462


In [26]:
from sklearn import metrics
print("MAE %2.f" %(np.sqrt(metrics.mean_absolute_error(y_test,y_pred))))

MAE 102


In [27]:
print('Train Score: %f' %(regressor.score(X_train, y_train))) 
print('Test Score: %f' % (regressor.score(X_test, y_test)) )

Train Score: 0.723921
Test Score: 0.702984


In [28]:
import pickle 
saved_model = pickle.dumps(regressor) 
saved_model = pickle.loads(saved_model) 
saved_model.predict(X_test)

array([136573.97892264, 118715.44349403, 124051.79103562, 150511.95533736,
       159088.61203976, 104912.77946275, 121850.76066938, 138904.03340243,
       104909.4257188 , 178575.99119541, 141217.50007135, 125660.97947056,
       147813.96583986, 122760.41522355, 136013.94960524, 103987.61384284,
       111838.19297562, 111144.10892875, 119781.16885   , 112451.83424256,
       111152.07407062, 178580.60259334, 105598.05993176, 137306.1638533 ,
       124053.46790759, 116511.47860183])

In [29]:
saved_model.predict(X_train)

array([151525.66183435, 116509.80172986, 105585.48339197, 139007.66612725,
       136001.37306545, 119747.41467385, 173241.73974379, 151525.66183435,
       105598.89836775, 122754.54617164, 137606.78853845, 101308.99215445,
       104898.52605098, 125090.46970333, 110246.19247839, 133660.83813583,
       119750.3491998 , 159072.68175602, 136929.05399331, 126011.8623613 ,
        93452.54396976, 118109.76736896, 133728.78727856, 118876.54491175,
       179655.13152717, 147810.61209592, 146555.52448492, 172321.60473979,
       137608.04619243, 148546.4154608 , 125996.77051356, 134726.56349181,
       166978.9689283 , 119391.50116719, 111857.05778531, 151512.66607656,
       105590.93322588, 155856.68723882, 160730.03230659, 110242.41951645,
       132652.16225476, 146550.91308699, 111157.94312252, 167146.35861592,
       130313.30419712, 125093.40422928, 210252.70172105, 151509.73155061,
       125999.28582151, 130654.54507403, 132652.16225476, 137268.06296951,
       117192.98610891, 1

In [30]:
import pickle 
print("[INFO] Saving model...")
saved_model=pickle.dump(regressor,open('/content/drive/My Drive/House_Price_Prediction.pkl', 'wb')) 

[INFO] Saving model...


In [31]:
import joblib
filename = '/content/drive/My Drive/House_Price_Prediction.sav'
joblib.dump(regressor, filename)
loaded_model = joblib.load(filename)
result = loaded_model.score(X_test, y_test)
result

0.7029844760312064

In [32]:
import pickle
model = pickle.load(open('/content/drive/My Drive/House_Price_Prediction.pkl','rb'))  
model.predict(X_test)

array([136573.97892264, 118715.44349403, 124051.79103562, 150511.95533736,
       159088.61203976, 104912.77946275, 121850.76066938, 138904.03340243,
       104909.4257188 , 178575.99119541, 141217.50007135, 125660.97947056,
       147813.96583986, 122760.41522355, 136013.94960524, 103987.61384284,
       111838.19297562, 111144.10892875, 119781.16885   , 112451.83424256,
       111152.07407062, 178580.60259334, 105598.05993176, 137306.1638533 ,
       124053.46790759, 116511.47860183])

In [33]:
%mkdir templates -p

In [34]:
%%writefile templates/index.html

# -*- coding: utf-8 -*-
"""
Created on Wed Jul 27 21:52:20 2022

@author: Hp
"""

%%writefile templates/index.html

<!DOCTYPE html>
<html >
<!--From https://codepen.io/frytyler/pen/EGdtg-->
<head>
<title>Machine Learning  Linear Regression Deployment</title>
<meta charset="UTF-8">
<link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"> 
<style><!DOCTYPE html>
h1 {text-align: center;}
h2 {text-align: center;}
h3 {text-align: center;}
p {text-align: center;}
div {text-align: center;}
</style>
</head>
<body>
<div class = ""style = "background-color:blue;">
<div class = "clearfix">
<div class="col-md-12">
<center><p style="font-size:40px;color:white;margin-top:10px;">Poornima Institute of Engineering & Technology</p></center> 
<center><p style="font-size:30px;color:white;margin-top:10px;">Department of Computer Engineering</p></center> 
<center><p style="font-size:25px;color:white;margin-top:10px;">Summer Internship 2022 on Machine learning and Data Science</p></center> 
</div>
<div class="login">
<h2 >Regression Analysis to predict Price basis</h2>
<h4>Developed by Nitish Nama</h4>
<!-- Main Input For Receiving Query to our ML -->
<form action="{{ url_for('predict')}}"method="get">
<div class="form-floating mb-3">
<input type="number" class="form-control" id="exp1" name="exp1" step="any" min="0" max="100000" placeholder="0" required="required">
<label for="floatingInput">Enter SqFt</label>
</div>
<div class="form-floating mb-3">
<input type="number" class="form-control" id="exp2" name="exp2" step="any" min="0" max="4" placeholder="0" required="required">
<label for="floatingInput">Enter Bedrooms</label>
</div>
<div class="form-floating mb-3">
<input type="number" class="form-control" id="exp3" name="exp3" step="any" min="0" max="3" placeholder="0" required="required">
<label for="floatingInput">Enter Bathrooms</label>
</div>
<div class="form-floating mb-3">
<input type="number" class="form-control" id="exp4" name="exp4" step="any" min="0" max="5" placeholder="0" required="required">
<label for="floatingInput">Enter Offers</label>
</div>
<div class="form-floating mb-3">
<input type="number" class="form-control" id="exp5" name="exp5" step="any" min="0" max="1" placeholder="0" required="required">
<label for="floatingInput">Enter Brick</label>
</div>
<div class="form-floating mb-3">
<input type="number" class="form-control" id="exp6" name="exp6" step="any" min="0" max="2" placeholder="0" required="required">
<label for="floatingInput">Enter Neighborhood</label>
</div>
<br>
<br>
<button type="submit" class="btn btn-primary btn-block btn-large">Predict Price</button>
</form>
<br>
<br>
{{ prediction_text }}
<div class="col-md-12">
 <center><p style="font-size:25px;color:white;margin-top:20px;">Experiment Performed in Summer internship 2022 from 27 June to 8 August </p></center> 
</div>
</div>
</div>
</body>
</html>

Writing templates/index.html


In [35]:
!pip install pyngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 761.3/761.3 KB 39.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pyngrok: filename=pyngrok-5.2.1-py3-none-any.whl size=19790 sha256=4e46c978abdec2d8025e784c72866666f316b15f3a1cf95a8d46befd14239b60
  Stored in directory: /root/.cache/pip/wheels/f6/89/59/49d4249e00957e94813ac136a335d10ed2e09a856c5096f95c
Successfully built pyngrok


In [36]:
!pip install flask-ngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [37]:
!ngrok authtoken 2CVhNfyL2r6AJch27wQDv3ZU2sS_5xJy1jAxddS4M8qkJmLPM

Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


In [ ]:
import numpy as np
from flask import Flask, request, jsonify, render_template
from flask_ngrok import run_with_ngrok
import pickle


app = Flask(__name__)
model = pickle.load(open('/content/drive/My Drive/House_Price_Prediction.pkl','rb')) 
run_with_ngrok(app)

@app.route('/')
def home():
  
    return render_template("index.html")
  
@app.route('/predict',methods=['GET'])
def predict():
    
    
    '''
    For rendering results on HTML GUI
    '''
    exp1 = float(request.args.get('exp1'))
    exp2 = float(request.args.get('exp2'))
    exp3 = float(request.args.get('exp3'))
    exp4 = float(request.args.get('exp4'))
    exp5 = float(request.args.get('exp5'))
    exp6 = float(request.args.get('exp5'))
    prediction = model.predict([[exp1,exp2,exp3,exp4,exp5,exp6]])
    
        
    return render_template('index.html', prediction_text='Regression Model  has predicted House Price  : {}'.format(prediction))

app.run()

 * Serving Flask app '__main__'
 * Debug mode: off


INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit


 * Running on http://8c94-34-150-152-53.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040


INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 08:17:45] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 08:17:46] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 08:18:13] "GET /predict?exp1=20000&exp2=2&exp3=1&exp4=0&exp5=1&exp6=1 HTTP/1.1" 200 -
